import {
  EPropertyType,
  ETenantType,
  // EAmenityType,
  // EPaymentMethod,
} from "../backend/casaikos-api";
// import {
//   ACIcon,
//   BalconyIcon,
//   TVIcon,
//   InternetIcon,
//   ParkingIcon,
//   SwimmingIcon,
//   GymIcon,
//   GardenIcon,
//   SecurityIcon,
//   LaundryIcon,
// } from "../icons";
// export const genders = ["Male", "Female"];

// export const honorificTitles = [
//   "Mr.",
//   "Mrs.",
//   "Miss",
//   "Ms.",
//   "Dr.",
//   "Sir",
//   "Lady",
// ];

// export const nationalities = [
//   "Afghan",
//   "Albanian",
//   "Algerian",
//   "American",
//   "Andorran",
//   "Angolan",
//   "Antiguans",
//   "Argentinean",
//   "Armenian",
//   "Australian",
//   "Austrian",
//   "Azerbaijani",
//   "Bahamian",
//   "Bahraini",
//   "Bangladeshi",
//   "Barbadian",
//   "Barbudans",
//   "Botswana",
//   "Belarusian",
//   "Belgian",
//   "Belizean",
//   "Beninese",
//   "Bhutanese",
//   "Bolivian",
//   "Bosnian",
//   "Brazilian",
//   "British",
//   "Bruneian",
//   "Bulgarian",
//   "Burkinabe",
//   "Burmese",
//   "Burundian",
//   "Cambodian",
//   "Cameroonian",
//   "Canadian",
//   "Cape Verdean",
//   "Central African",
//   "Chadian",
//   "Chilean",
//   "Chinese",
//   "Colombian",
//   "Comoran",
//   "Congolese",
//   "Costa Rican",
//   "Croatian",
//   "Cuban",
//   "Cypriot",
//   "Czech",
//   "Danish",
//   "Djibouti",
//   "Dominican",
//   "Dutch",
//   "East Timorese",
//   "Ecuadorean",
//   "Egyptian",
//   "Emirian",
//   "Equatorial Guinean",
//   "Eritrean",
//   "Estonian",
//   "Ethiopian",
//   "Fijian",
//   "Filipino",
//   "Finnish",
//   "French",
//   "Gabonese",
//   "Gambian",
//   "Georgian",
//   "German",
//   "Ghanaian",
//   "Greek",
//   "Grenadian",
//   "Guatemalan",
//   "Guinea-Bissauan",
//   "Guinean",
//   "Guyanese",
//   "Haitian",
//   "Herzegovinian",
//   "Honduran",
//   "Hungarian",
//   "I-Kiribati",
//   "Icelander",
//   "Indian",
//   "Indonesian",
//   "Iranian",
//   "Iraqi",
//   "Irish",
//   "Israeli",
//   "Italian",
//   "Ivorian",
//   "Jamaican",
//   "Japanese",
//   "Jordanian",
//   "Kazakhstani",
//   "Kenyan",
//   "Kittian and Nevisian",
//   "Kuwaiti",
//   "Kyrgyz",
//   "Laotian",
//   "Latvian",
//   "Lebanese",
//   "Liberian",
//   "Libyan",
//   "Liechtensteiner",
//   "Lithuanian",
//   "Luxembourger",
//   "Macedonian",
//   "Malagasy",
//   "Malawian",
//   "Malaysian",
//   "Maldivan",
//   "Malian",
//   "Maltese",
//   "Marshallese",
//   "Mauritanian",
//   "Mauritian",
//   "Mexican",
//   "Micronesian",
//   "Moldovan",
//   "Monacan",
//   "Mongolian",
//   "Moroccan",
//   "Mosotho",
//   "Motswana",
//   "Mozambican",
//   "Namibian",
//   "Nauruan",
//   "Nepalese",
//   "New Zealander",
//   "Nicaraguan",
//   "Nigerian",
//   "Nigerien",
//   "North Korean",
//   "Northern Irish",
//   "Norwegian",
//   "Omani",
//   "Pakistani",
//   "Palauan",
//   "Panamanian",
//   "Papua New Guinean",
//   "Paraguayan",
//   "Peruvian",
//   "Polish",
//   "Portuguese",
//   "Qatari",
//   "Romanian",
//   "Russian",
//   "Rwandan",
//   "Saint Lucian",
//   "Salvadoran",
//   "Samoan",
//   "San Marinese",
//   "Sao Tomean",
//   "Saudi",
//   "Scottish",
//   "Senegalese",
//   "Serbian",
//   "Seychellois",
//   "Sierra Leonean",
//   "Singaporean",
//   "Slovakian",
//   "Slovenian",
//   "Solomon Islander",
//   "Somali",
//   "South African",
//   "South Korean",
//   "Spanish",
//   "Sri Lankan",
//   "Sudanese",
//   "Surinamer",
//   "Swazi",
//   "Swedish",
//   "Swiss",
//   "Syrian",
//   "Taiwanese",
//   "Tajik",
//   "Tanzanian",
//   "Thai",
//   "Togolese",
//   "Tongan",
//   "Trinidadian or Tobagonian",
//   "Tunisian",
//   "Turkish",
//   "Tuvaluan",
//   "Ugandan",
//   "Ukrainian",
//   "Uruguayan",
//   "Uzbekistani",
//   "Venezuelan",
//   "Vietnamese",
//   "Welsh",
//   "Yemenite",
//   "Zambian",
//   "Zimbabwean",
// ];

// export const durations = [
//   { label: "15 min", value: 900 },
//   { label: "30 min", value: 1800 },
//   { label: "45 min", value: 2700 },
//   { label: "1 hour", value: 3600 },
//   { label: "1 hour and 15 min", value: 4500 },
//   { label: "1 hour and 30 min", value: 5400 },
//   { label: "1 hour and 45 min", value: 6300 },
//   { label: "2 hours", value: 7200 },
//   { label: "2 hours and 15 min", value: 8100 },
//   { label: "2 hours and 30 min", value: 9000 },
//   { label: "2 hours and 45 min", value: 9900 },
//   { label: "3 hours", value: 10800 },
// ];

// export const daysTitleList = [
//   { label: "Mon", value: 1 },
//   { label: "Tue", value: 2 },
//   { label: "Wed", value: 3 },
//   { label: "Thu", value: 4 },
//   { label: "Fri", value: 5 },
//   { label: "Sat", value: 6 },
//   { label: "Sun", value: 7 },
// ];

export const monthsList = [
  { label: "January", value: 1 },
  { label: "February", value: 2 },
  { label: "March", value: 3 },
  { label: "April", value: 4 },
  { label: "May", value: 5 },
  { label: "June", value: 6 },
  { label: "July", value: 7 },
  { label: "August", value: 8 },
  { label: "September", value: 9 },
  { label: "October", value: 10 },
  { label: "November", value: 11 },
  { label: "December", value: 12 },
];

// export const daysOfWeekOptions = [
//   { label: "Sunday", value: 0 },
//   { label: "Monday", value: 1 },
//   { label: "Tuesday", value: 2 },
//   { label: "Wednesday", value: 3 },
//   { label: "Thursday", value: 4 },
//   { label: "Friday", value: 5 },
//   { label: "Saturday", value: 6 },
// ];

export const propertyTypesOptions = [
  { label: "Apartment", value: EPropertyType.APARTMENT },
  { label: "House", value: EPropertyType.HOUSE },
  { label: "Studio", value: EPropertyType.STUDIO },
  { label: "Villa", value: EPropertyType.VILLA },
  { label: "Penthouse", value: EPropertyType.PENTHOUSE },
  { label: "Townhouse", value: EPropertyType.TOWNHOUSE },
];

export const tenantTypesOptions = [
  { label: "Family", value: ETenantType.FAMILY },
  { label: "Bachelors", value: ETenantType.BACHELORS },
  { label: "Mixed", value: ETenantType.MIXED },
  { label: "Professionals", value: ETenantType.PROFESSIONALS },
  { label: "Students", value: ETenantType.STUDENTS },
];

// export const paymentMethodsList = Object.values(EPaymentMethod);
// export const propertyTypes = Object.values(EPropertyType);
// export const tenantTypes = Object.values(ETenantType);
// export const amenitiesTypes = Object.values(EAmenityType);

// export const amenitiesList = [
//   {
//     label: EAmenityType.AirConditioning,
//     icon: ACIcon,
//   },
//   {
//     label: EAmenityType.CableTV,
//     icon: TVIcon,
//   },
//   {
//     label: EAmenityType.Internet,
//     icon: InternetIcon,
//   },
//   {
//     label: EAmenityType.Balcony,
//     icon: BalconyIcon,
//   },
//   {
//     label: EAmenityType.Parking,
//     icon: ParkingIcon,
//   },
//   {
//     label: EAmenityType.PetsAllowed,
//     icon: ParkingIcon,
//   },
//   {
//     label: EAmenityType.SwimmingPool,
//     icon: SwimmingIcon,
//   },
//   {
//     label: EAmenityType.Gym,
//     icon: GymIcon,
//   },
//   {
//     label: EAmenityType.Garden,
//     icon: GardenIcon,
//   },
//   {
//     label: EAmenityType.Security,
//     icon: SecurityIcon,
//   },
//   // {
//   //   label: EAmenityType.MailService,
//   //   icon: MailSIcon,
//   // },
//   {
//     label: EAmenityType.Laundry,
//     icon: LaundryIcon,
//   },
// ];

export const targetYears = Array.from(
  { length: new Date().getFullYear() - 2015 + 1 },
  (_, i) => 2015 + i
);
